spring:
  application:
    name: linkgrove-api


server:
  port: 8080
  error:
    include-stacktrace: on_trace_param
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      
jwt:
  secret: linkgroveSecretKeyForJWTTokenGeneration2024
  expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    org:
      springframework:
        security: DEBUG

