version: '3.8'

services:
  postgres:
    image: postgres:15.8-alpine
    container_name: linkgrove-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=linkgrove
      - POSTGRES_PASSWORD=linkgrove
      - POSTGRES_DB=linkgrove
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkgrove -d linkgrove"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4-alpine
    container_name: linkgrove-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: linkgrove-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: linkgrove-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/linkgrove}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-linkgrove}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-linkgrove}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST:-redis}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT:-6379}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST:-redis}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT:-6379}
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST:-rabbitmq}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT:-5672}
      - JWT_SECRET=${JWT_SECRET:-linkgrove_dev_secret_key_0123456789abcdef0123456789abcdef}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3001}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://localhost:3001}
      - TWITTER_SITE=${TWITTER_SITE:-}
    depends_on:
      - postgres
      - redis
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-/api}
    container_name: linkgrove-frontend
    ports:
      - "3001:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

