version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: linkgrove-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=linkgrove
      - POSTGRES_PASSWORD=linkgrove
      - POSTGRES_DB=linkgrove
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkgrove -d linkgrove"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: linkgrove-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: linkgrove-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: linkgrove-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/linkgrove}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-linkgrove}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-linkgrove}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST:-redis}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT:-6379}
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST:-rabbitmq}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT:-5672}
      - JWT_SECRET=${JWT_SECRET:-change-me-in-prod}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://example.com,https://www.example.com}
    depends_on:
      - postgres
      - redis
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: linkgrove-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://backend:8080}
    depends_on:
      - backend
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

