ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS bio VARCHAR(500),
  ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(200),
  ADD COLUMN IF NOT EXISTS theme_primary_color VARCHAR(20),
  ADD COLUMN IF NOT EXISTS theme_accent_color VARCHAR(20),
  ADD COLUMN IF NOT EXISTS theme_background_color VARCHAR(20),
  ADD COLUMN IF NOT EXISTS theme_text_color VARCHAR(20);


