spring:
  application:
    name: linkgrove-api
  datasource:
    url: jdbc:postgresql://localhost:5432/linkgrove
    username: linkgrove
    password: linkgrove
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 3
          max-interval: 10000ms

server:
  port: 8080

jwt:
  secret: linkgroveSecretKeyForJWTTokenGeneration2024
  expiration: 86400000
