spring:
  application:
    name: linkgrove-api
  datasource:
    url: jdbc:postgresql://localhost:5432/linkgrove
    username: linkgrove
    password: linkgrove
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-version: 0
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:${SPRING_REDIS_HOST:localhost}}
      port: ${SPRING_DATA_REDIS_PORT:${SPRING_REDIS_PORT:6379}}
      timeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jdbc.connections: true
        webhook.emit.time: true
        webhook.resend.time: true
        analytics.process.time: true
        analytics.queue.lag.seconds: true
      slo:
        http.server.requests: 100ms,250ms,500ms,1s,2s,5s
    export:
      prometheus:
        enabled: ${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:true}
        exemplars:
          enabled: true
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: ${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:true}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 3
          max-interval: 10000ms

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
  http:
    headers:
      hsts:
        max-age: 31536000
        include-sub-domains: true
        preload: true

jwt:
  secret: ${JWT_SECRET:linkgroveSecretKeyForJWTTokenGeneration2024}
  expiration: 86400000

webhooks:
  maxRetriesPerDestinationPerDay: 100

public:
  base-url: ${PUBLIC_BASE_URL:}

twitter:
  site: ${TWITTER_SITE:}
