spring:
  application:
    name: linkgrove-api
  datasource:
    url: jdbc:postgresql://localhost:5432/linkgrove
    username: linkgrove
    password: linkgrove
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 3
          max-interval: 10000ms

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
  http:
    headers:
      hsts:
        max-age: 31536000
        include-sub-domains: true
        preload: true

jwt:
  secret: ${JWT_SECRET:linkgroveSecretKeyForJWTTokenGeneration2024}
  expiration: 86400000

webhooks:
  maxRetriesPerDestinationPerDay: 100
